@HOST=http://localhost:8080

###
POST {{HOST}}/file/upload
Content-Type: multipart/form-data

{
  "file": "@./photo/daniel-sessler-pX5PxHC1aEM-unsplash.jpg"
}

###
GET {{HOST}}/file/explorer

###
GET {{HOST}}/file/view/abc.png

###
GET {{HOST}}/file/download/abc.png


